export const requirementOptions = [
  { label: "Italian", value: "italian" },
  { label: "German", value: "german" },
  { label: "Spanish", value: "spanish" },
  { label: "UK based", value: "uk-based" },
  { label: "German based", value: "german-based" },
  { label: "Spain based", value: "spain-based" },
  { label: "Holland based", value: "holland-based" },
];

export const AEs = [
  // -- UK
  { label: "Jordan Chandler", value: "jordan.chandler@vercel.com", segment: "MM", region: "UK" },
  { label: "Oliver Pollins", value: "oliver.pollins@vercel.com", segment: "ENT", region: "UK" },
  {
    label: "Zachary Chukwumah",
    value: "zachary.chukwumah@vercel.com",
    segment: "MM",
    region: "UK",
  },
  { label: "Theo Khoja", value: "theo.khoja@vercel.com", segment: "ENT", region: "UK" },
  { label: "Yan Pineda", value: "yan.pineda@vercel.com", segment: "MM", region: "UK" },
  // -- DACH
  { label: "Julian Eckerle", value: "julian.eckerle@vercel.com", segment: "ENT", region: "DACH" },
  { label: "Stefan Nikolic", value: "stefan.nikolic@vercel.com", segment: "MM", region: "DACH" },
  { label: "Jonas Woehrle", value: "jonas.woehrle@vercel.com", segment: "MM", region: "DACH" },
  { label: "Lasse Pedersen", value: "lasse.pedersen@vercel.com", segment: "MM", region: "DACH" },
  // -- NS
  { label: "Erica Couto", value: "erica.couto@vercel.com", segment: "ENT", region: "NS" },
  { label: "Megan Wilke", value: "megan.wilke@vercel.com", segment: "MM", region: "NS" },
  { label: "Erlend Fredsted", value: "erica.couto@vercel.com", segment: "MM", region: "NS" },
  { label: "David Merino", value: "david.merino@vercel.com", segment: "ENT", region: "NS" },
  { label: "Oskar Munch", value: "oskar.munch@vercel.com", segment: "MM", region: "NS" },
];

export const SEs = [
  { label: "Alice De Mauro", value: "Alice De Mauro" },
  { label: "Matt Reid", value: "Matt Reid" },
  { label: "Matt Froggett", value: "Matt Froggett" },
  { label: "Yi Min Yang", value: "Yi Min Yang" },
  { label: "Miguel Alcalde", value: "Miguel Alcalde" },
  { label: "Farhan Ali", value: "Farhan Ali" },
];

export const companyNames = [
  "TechWave Solutions",
  "Skyline Innovations",
  "BrightPath Media",
  "GreenField Ventures",
  "NextGen Analytics",
  "Visionary Labs",
  "PrimeCore Systems",
  "BlueStream Technologies",
  "EcoSphere Consulting",
  "Elevate Synergy",
  "FusionPoint Industries",
  "Apex Dynamics",
  "SparkWave Digital",
  "Zenith Global",
  "QuantumByte Corp",
  "UrbanForge Solutions",
  "NexaSoft Enterprises",
  "EverBright Consultancy",
  "OmniWorks",
  "Dynamic Edge",
  "MotiveQuest Ventures",
  "ClearPath Technologies",
  "Peakwise Solutions",
  "ProSync Innovations",
  "VibrantWave Solutions",
  "InsightEdge Analytics",
  "SwiftLink Networks",
  "CorePulse Dynamics",
  "EcoVantage Group",
  "NovaSphere Tech",
  "BrightMind Innovations",
  "FrontierLab Solutions",
  "Transcend Systems",
  "BlueHorizon Industries",
  "LunaTech Enterprises",
  "NextWave Solutions",
  "Catalyst Logic",
  "AspireCloud Technologies",
  "Infinity Solutions",
  "ProVision Media",
  "VertexTech",
  "Silverline Analytics",
  "EcoWise Solutions",
  "ZenithEdge Dynamics",
  "AlphaForge Group",
  "InnovaNet Systems",
  "RadiantPath",
  "QuantumVista",
  "PeakSphere Dynamics",
  "UnityWorks Group",
  "OptiSolutions Inc",
];
